title: 甯的个人网站
author: 甯
email: 2592455945@qq.com
description: 互联网上的一处静谧旷野

# social links
twitter_username: Frank_N1ng # DO NOT include the @ character, or else the build will fail!
github_username:  Frank-N1ng # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
